Channels:
  shooter_channel: 1
  controller_port: 0

# Currently optimized for an xbox one controller
Controller:
  left_trigger_axis: 2
  right_trigger_axis: 5
  a_button_num: 1 # button numbers start at 1 for some godforsaken reason
  b_button_num: 2
  x_button_num: 3
  y_button_num: 4
